### ISSUE TITLE
Possible error in Readme?

### ISSUE THREAD

**Issue by gkalafut** [erikw/restic-systemd-automatic-backup#1]
New to all this linux stuff, so excuse me if this is incorrect - but you state that the email address should be swapped in systemd-email, even though it accepts the email address as a variable that you set as recipinent. It seems to me after an hour of poking around and checking the pages you list for source that the email address should actually be specified in status-email-user@.service. Testing this functions properly; running 
`systemd-email "myemail@gmail.com" "test"` 
generates an email to my inbox.

**Comment by erikw** [comment]
Hey! You are completely right, I wrote wrong in the README. I will fix it soon.

Thanks for report the mistake :)
