### ISSUE TITLE
Easier configuration

### ISSUE THREAD

**Issue by lahdekorpi** [erikw/restic-systemd-automatic-backup#12]
Would it be ok to move the configuration related environmental variables from the `/usr/local/sbin/restic_backup.sh` to something like `/etc/restic/backup_env.sh` to make it more "unix like" and somewhat easier to configure?  
Clearly a very minor change, but just wanted to check before making a PR.

These:
```bash
RETENTION_DAYS
RETENTION_WEEKS
RETENTION_MONTHS
RETENTION_YEARS
BACKUP_PATHS
BACKUP_EXCLUDES
```

**Comment by erikw** [comment]
Good idea! I would pick a new file rather than `/etc/restic/backup_env.sh` though, as this one is also used on interactive command line to work with `restic(1)` by sourcing this file.

Maybe a new file `/etc/restic/bacup_settings.sh` or the like, that is sourced from the backup scripts?

**Comment by peperunas** [comment]
Hello!
I have been using "env" files to manage multiple backups, [click](https://github.com/peperunas/configs/tree/master/restic). My method uses systemd's "@" feature to load different configs for restic. 
Maybe we could move the configuration to external files as @lahdekorpi suggested and then use systemd's "@" operator.

Does it make sense to you?

**Comment by lahdekorpi** [comment]
@peperunas Sound great!

Maybe we just load the configuration (or "env") file from the restic directory under etc with the name provided after the systemd @ character?  
Should be simple enough to implement.

**Comment by erikw** [comment]
Loading different config sound like a good idea 👍

**Comment by peperunas** [comment]
@lahdekorpi that was exactly what I was thinking. :-)

**Comment by lahdekorpi** [comment]
I'm now thinking if making even the repository type for restic configurable. Or at least easy to extend.  
But a separate `restic_backup.sh` file for each type or a lot of if statements..? 🤔

**Comment by erikw** [comment]
@lahdekorpi Hm at this still small size, I think we could stick to one script still, but utilize shell functions for code structure, check out out my repo here for example: https://github.com/erikw/tmux-powerline/blob/master/segments/now_playing.sh#L59-L72

**Comment by mfeif** [comment]
This is sounding great! I have 3 different B2 repositories, each mapped to a mountpoint, so this software AS-IS is hard for me to use, but if I could have 3 different env sets, that would be excellent.

Can I help push this along? My bash foo is not great... but I can try.

**Comment by erikw** [comment]
As a note to self; after merging this, the AUR PKGBUILD must be updated with the new file paths:

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=restic-systemd-automatic-backup
