### ISSUE TITLE
Duplicate of Backupninja?

### ISSUE THREAD

**Issue by colans** [erikw/restic-systemd-automatic-backup#24]
Does this project do anything above and beyond what [Backupninja](https://0xacab.org/riseuplabs/backupninja) does?  Once [Restic support](https://0xacab.org/riseuplabs/backupninja/merge_requests/17) gets in, would it still be useful?

This was originally mentioned in restic/restic/issues/519.

**Comment by erikw** [comment]
Duplicate? The answer is no. This project aims to be a simple setup for systemd systems, while the other project has a larger scope :=)

**Comment by colans** [comment]
Thanks for the clarification.  I suggested that we add this project to the list of options in a new Scheduling section of the Restic manual (see Restic issue above).

**Comment by colans** [comment]
If you agree that makes sense, please add your support there. :)
