### ISSUE TITLE
Small mistake in README

### ISSUE THREAD

**Issue by danmanirl** [erikw/restic-systemd-automatic-backup#25]
HI,

A small correction that might help avoid confusion, [this section](https://github.com/erikw/restic-systemd-automatic-backup#2-configure-your-b2-account-locally) calls for the B2 password to be stored in plaintext in the file.

The password to be stored in `b2_pw.txt` is actually the _restic repository password_ and should probably *not* be the same as your B2 password.

So I propose to have the following text instead of "Put your B2 password in this file.":

> This file should contain the restic repository password which is unique to this restic backup repository and is needed for restoring from it.

**Comment by erikw** [comment]
You're right! Thanks for pointing it out. Fixed

**Comment by danmanirl** [comment]
👍

Thanks for sharing your setup, really useful repo
