### ISSUE TITLE
restic_backup.sh - is this right?

### ISSUE THREAD

**Issue by null-burn** [erikw/restic-systemd-automatic-backup#31]
First time user... I opened restic_backup.sh and saw this. Which is right?

"
How many network connections to set up to B2. Default is 5.
B2_CONNECTIONS=50
"

**Comment by erikw** [comment]
Check out this help article: https://help.backblaze.com/hc/en-us/articles/115002880514-How-to-configure-Backblaze-B2-with-Restic-on-Linux?mobile_site=true

Search for b2.connections there :)

**Comment by null-burn** [comment]
Sorry maybe I didn't explain it very well. It was more on the language being used shouldn't "How many network connections to set up to B2. Default is 5." be "How many network connections to set up to B2. Default is **50**." Since this script defaults it to 50. Thanks.

**Comment by erikw** [comment]
I believe the default value in restic for `b2.connections` is `5`. From the article I linked above it says

> By default, at most five parallel connections are established.

**Comment by lukastribus** [comment]
I believe @null-burn is referring to the fact that the scrip in *this* repo, sets `B2_CONNECTIONS=50` twice:

https://github.com/erikw/restic-systemd-automatic-backup/blob/be6ab0c37a3fea08b4a4b8945449c6be7a9cf804/usr/local/sbin/restic_check.sh#L22
https://github.com/erikw/restic-systemd-automatic-backup/blob/be6ab0c37a3fea08b4a4b8945449c6be7a9cf804/usr/local/sbin/restic_backup.sh#L44

**Comment by erikw** [comment]
Oh that's fine, these are both two top-level scripts that don't source or call each other. So that `restic_check.sh` sets `b2.connections` does not affect that `restic_backup.sh` sets the same :-)
