### ISSUE TITLE
newbie question

### ISSUE THREAD

**Issue by ctenuun** [erikw/restic-systemd-automatic-backup#33]
Can someone help me configure paths ?
BACKUP_PATHS="/opt/my_app"

what does this part mean ? [ -d /mnt/media ] && BACKUP_PATHS+=" /mnt/media" 
Can i comment out this part? do i even need /mnt/media dir ?

Thanks for helpingout this newb.

**Comment by erikw** [comment]
`BACKUP_PATHS="/opt/my_app"`
is enough

The 2nd line just adds /mnt/media if it exists. Comment it out or let it be if this path does not exist.
