### ISSUE TITLE
Backup paths question

### ISSUE THREAD

**Issue by nomad101** [erikw/restic-systemd-automatic-backup#34]
Hello, thanks for this - it's really helpful.

Though I'm a still a bit of an inexperienced linux user and not sure how to add backup paths. 
I have two folders I would like to backup up into separate buckets on B2:
```
/home/osmc/media-drive/backup1
/home/osmc/media-drive/backup2
```
How should I amend the code below, and what to do for two buckets:

```
BACKUP_PATHS="/ /boot /home"
[ -d /mnt/media ] && BACKUP_PATHS+=" /mnt/media"
```

Could you please show an example with my back up path?
Sorry for the dumb request - any help will be appreciated. 

Thanks

**Comment by erikw** [comment]
Hey, 
To backup /home/osmc/media-drive/backup1 you would set 
BACKUP_PATHS="/home/osmc/media-drive/backup1"

If you want 2 different buckets for different paths, you would need to create 2 configurations 

https://github.com/erikw/restic-systemd-automatic-backup/tree/master/etc/restic

and make a copy of the backup script itself.


This project is centered around using 1 B2 bucket but you for sure can modify it to use multiple
