### ISSUE TITLE
What this line does?

### ISSUE THREAD

**Issue by dikkatdeli** [erikw/restic-systemd-automatic-backup#42]
Hi,

can you tell me what this line does?

[ -d /mnt/media ] && BACKUP_PATHS+=" /mnt/media"

**Comment by erikw** [comment]
Hello,

this line is an example of how to add paths to backup dynamically.

`[ -d /mnt/media ]`
 is a bash expression that returns true if there is a directory `/mnt/media`.

`&& BACKUP_PATHS+=" /mnt/media"`
will run if the previous part returned true. It will then append the path to the string in `BACKUP_PATHS`

It's intended that you can customize this script to include which paths that you want. You can easily remove this line and just configure it statically on the line

`BACKUP_PATHS="/ /boot /home"`

Does that clarify? :)

**Comment by dikkatdeli** [comment]
Thank you so much. I learn new things. 

I have a question about the RETENTION system.

I want to keep :

the last 7 days daily backups after that I want to add 4 days then 7th day's backups and kept 11th days backup. I want to increase days like irrational. 3,5,7,9,11, etc. After the 7th daily backup.

How can I do that?

**Comment by erikw** [comment]
This script uses restic's built-in retention functionality. See
https://github.com/erikw/restic-systemd-automatic-backup/blob/master/usr/local/sbin/restic_backup.sh#L18-L22
and
https://github.com/erikw/restic-systemd-automatic-backup/blob/master/usr/local/sbin/restic_backup.sh#L74-L83

The official documentation is here:
https://restic.readthedocs.io/en/stable/060_forget.html

and as you see there are a few more parameters that you can modify the script `restic_backup.sh` to use to your liking like using the `--keep-last n`.

I don't think your example above would be possible to get with the built-in retention system in `restic forget`, but you could script your own retention system by removing specific old snapshots yourself with `restic forget #snapshotid`. 

This would be outside of the scope of this project though :)

For further questions about restic, I would refer to the official manual above.

**Comment by dikkatdeli** [comment]
Thank you I will read carefully.

About sending an email when its fails, I change the abc@gmail.com with my email in status-email-user@.service.

Is there a way to see if it sends email ?
