### ISSUE TITLE
make install twice ends in error

### ISSUE THREAD

**Issue by gerardbosch** [erikw/restic-systemd-automatic-backup#46]
Hi there! :wave:

I think the following problem was introduced in https://github.com/erikw/restic-systemd-automatic-backup/pull/41/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R6

or maybe the root cause comes from here https://github.com/erikw/restic-systemd-automatic-backup/pull/15

Run `sudo make install` and again `sudo make install`. The second time you run it you get:

```console
install -d /tmp/a/b/usr/local/sbin
install -m 0744 usr/local/sbin/nm-unmetered-connection.sh usr/local/sbin/restic_backup.sh usr/local/sbin/restic_check.sh usr/local/sbin/systemd-email /tmp/a/b/usr/local/sbin
install -d /tmp/a/b/etc/restic
install -m 0600 etc/restic/b2_env.sh  etc/restic/b2_env.sh etc/restic/b2_pw.txt  etc/restic/b2_pw.txt etc/restic/backup_exclude /tmp/a/b/etc/restic
install: will not overwrite just-created '/tmp/a/b/etc/restic/b2_env.sh' with 'etc/restic/b2_env.sh'
install: will not overwrite just-created '/tmp/a/b/etc/restic/b2_pw.txt' with 'etc/restic/b2_pw.txt'
make: *** [Makefile:45: install-conf] Error 1
```

This is because once `make install` has run once, `SRCS_CONF = $(patsubst %.template, %, $(wildcard etc/restic/*))` expands to duplicated file names that fail on `cp/install` command, as 2 input files with the same name cannot be copied into the same directory –actually only a single file exists, but the macro seems to expand wrongly as consider both `%.template` and `*`.

---

After looking at this, I'm not very clear what's the purpose of copying (and then keeping) the `*.template` files into repository's directory: `etc/restic/b2_env.sh` and `etc/restic/b2_pwd.txt`, as these files are already installed into the system directories.

What do you think is the best way to fix this? I guess one option would be to get rid of the  non-template files in `etc/restic`, but I'm not sure if that was introduced on purpose or as a tactical thing to fix something [here](https://github.com/erikw/restic-systemd-automatic-backup/pull/41/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R38) :)

**Comment by erikw** [comment]
Hello,

thank you for reporting this. I created a PR fix #48. Could you try out the fix to see if it works also for you?

**Comment by gerardbosch** [comment]
My pleasure! One more thing, I'm still a little confused about this:

> After looking at this, I'm not very clear what's the purpose of copying (and then keeping) the *.template files into repository's directory: etc/restic/b2_env.sh and etc/restic/b2_pwd.txt, as these files are already installed into the system directories.

After `sudo make install`, aren't you directly editing the target system files `/etc/restic/b2_pw.txt` and `/etc/restic/b2_env.sh`? So what's the point of the repository-local ones?

Thx!! :)

**Comment by erikw** [comment]
The feature comes from #15 like you already found. The idea is that many people fork this repostirory, and it would be a catastrophic if someone accidentally committed their `b2_pw.txt` in their fork with their password. The idea to prevent this, was to make a template with a different name, and .gitignore 

https://github.com/erikw/restic-systemd-automatic-backup/blob/master/.gitignore#L1-L3

theses sensitive files in the local repo in case a user/fork would have them edited.


As you say, it would be enough to do just copy local `b2_pw.txt.template` to the target `$PREFIX/etc/restic/b2_pw.txt`, but as far as I understand the manual of `install(1)`, it does not have the feature of renaming files. Thus a local file `b2_pw.txt` must exist.

I guess one could use `cp`, but the nice features of `install(1)` like setting permissions, or not overwriting existing config, is quite convenient.

We could however delete the local generated files after they have been installed, thus updating the install target for confs to

```diff
 install-conf: | $(SRCS_CONF)
 	install -d $(DEST_CONF)
  	install -m 0600 $(SRCS_CONF) $(DEST_CONF)
+	$(RM) etc/restic/b2_env.sh etc/restic/b2_pw.txt

```


What do you think @gerardbosch ? )

**Comment by gerardbosch** [comment]
Yey! I think that your suggestion to do a clean up is a good approach as looks less confusing not leaving unused files behind after `make`.

> but as far as I understand the manual of install(1), it does not have the feature of renaming files. Thus a local file b2_pw.txt must exist.

I don't know much about GNU Make, but do you think that something like this would work? (or if not maybe a `cp` and `chmod`)

```
install -m 0600 $(patsubst %.template, %, $(SRCS_CONF)) $(DEST_CONF)
```

I'd like to help with improvements and ideas if you like (I've got something that may help improving the UX of running restic with this setup), so I could have a look at this specific point with no problem. I guess you've seen a PR I opened yesterday :)

Just let me know :))

**Comment by gerardbosch** [comment]
Oh! I realise the above will not work on install, as there's no such file to install :sweat_smile: 

Maybe sth like this?

```
@for file in $(INSTALLED_FILES); do \
    install -m 0600 $$file $(DEST_CONF)/$(patsubst %.template, %, $$file)
done
```

But probably the `$(RM)` is the more simple way :D

**Comment by erikw** [comment]
@gerardbosch I pushed the `$(RM)` approach now.

Yes I've seen #45. I will get to it and look at it properly! I'm working on my email inbox as a stack right now :)
