### ISSUE TITLE
Add support for macOS

### ISSUE THREAD

**Issue by erikw** [erikw/restic-systemd-automatic-backup#51]
As discussed in #47, I already have it running on a mac system for several years. However as a cron job. 

* Add instructions on how to set up on a mac in `/usr/local/`. #49 is a blocker for this
* Create a proper solution using [LaunchAgents](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/ScheduledJobs.html#//apple_ref/doc/uid/10000172i-CH1-SW2)
* Integrate with the Makefile, maybe `$ make install-launchagent` ?
* Create a Homebrew Formula in my tap https://github.com/erikw/homebrew-tap

**Comment by gerardbosch** [comment]
Just for curiosity :) Is there much benefit by using LaunchAgents over cron?

**Comment by erikw** [comment]
I've not used LaunchAgent for timers yet (but I do for services), so I don't know yet. But I suspect that it will give nicer features just like systemd timers gives over cron.

https://apple.stackexchange.com/a/409334/197493

To be investigated :)
