### ISSUE TITLE
Rename backup_exclude to backup_exclude.txt

### ISSUE THREAD

**Issue by erikw** [erikw/restic-systemd-automatic-backup#64]
for next major release

**Comment by gerardbosch** [comment]
Just for my curiosity, why is that? :smile: 
Many config files in UNIX has no extension, `.gitignore`, `Makefile`, `.editorconfig`, `Jenkinsfile`.

I'm sure you have a reason for such breaking change, hehe.

**Comment by erikw** [comment]
While not mandatory in UNIX, still editors or GUI filebrowsers look at file extension to give hints to the user on what file it is or how it should be opened.

I'm living in a shell myself, but as support for both macOS and Windows is coming, I see it's more relevant :)

**Comment by gerardbosch** [comment]
That's what I was thinking :) thanks for the tip!! hehe
