### ISSUE TITLE
Installation via Homebrew

### ISSUE THREAD

**Issue by erikw** [erikw/restic-systemd-automatic-backup#73]
Following up from #51, create a Homebrew Formula in my tap https://github.com/erikw/homebrew-tap

**Comment by gerardbosch** [comment]
Hi again :) More questions, hehe.
I've been playing with Nix package manager recently, which also works on both Linux and MacOS. I'm still evaluating it, but there are certain things that I find great, mainly the hash-based immutable dependencies.

Do you think it would make sense to try publishing into Nix? I have to say that I've got zero idea how to do that, but currently I'm installing all the system packages I can from there (it has more than 70,000 packages, although I think this includes the Perl CPAN ones, and other language libraries).

**Comment by erikw** [comment]
Maybe that. I'm using Arch's AUR and Homebrew, that's why I've focused on them here

I've only read about nix but not try used it myself.

If it's easy to maintain, why not :)

**Comment by erikw** [comment]
Work in progress at https://github.com/erikw/homebrew-tap/tree/formula_restic
